name: CustomTP
main: jp.kentan.minecraft.tp.CustomTP
version: 1.0.0
author: ken_kentan
website: http://ken.kentan.jp

commands:
    stp:
        description: TPを設定します
        usage: /stp <数字(0~9)/time 数字(0~9)>
        permission: jp.kentan.minecraft.tp
        permission-message: You don't have <permission>
    ctp:
        description: 設定した場所にTPします
        usage: /ctp <Player>
        permission: jp.kentan.minecraft.tp
        permission-message: You don't have <permission>
